name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_publish:
    runs-on: ubuntu-latest
    container:
      image: oven/bun:1.2-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun test

      - name: Publish package with build in prepublish
        run: bun run publish_pkg
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify package version
        run: bun info @pencroff-lab/wyhash-ts
        env:
          NPM_TOKEN: "---"
